# SonarQube server configuration
sonar.host.url=http://<SONAR_EC2_IP>:9000 #You can write your IP here
sonar.login=<SONAR_TOKEN> #Your sonarqube token

# Project-specific configuration (example)
sonar.projectKey=MyProject
sonar.projectName=MyProject
sonar.projectVersion=1.0

# Source code paths
sonar.sources=src
sonar.java.binaries=target/classes



